/*
 *
 * Leagues constants
 *
 */

export const DEFAULT_ACTION = 'app/Leagues/DEFAULT_ACTION';

export const ACTIONS = {
  FETCH_LEAGUES: 'FETCH_LEAGUES',
  ADD_LEAGUES: 'ADD_LEAGUES',
  UPDATE_FORM: 'UPDATE_LEAGUE_FORM',
  UPDATE_LEAGUES: 'UPDATE_LEAGUES',
}
